// レンダラーに公開する API（window.api）
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  engineStart: path => ipcRenderer.invoke('engine:start', path),
  engineSend: (id, line) => ipcRenderer.send('engine:send', id, line),
  engineKill: id => ipcRenderer.send('engine:kill', id),
  engineDefaults: () => ipcRenderer.invoke('engine:defaults'),
  engineExists: p => ipcRenderer.invoke('engine:exists', p),
  onEngineLine: cb => ipcRenderer.on('engine:line', (_e, id, line) => cb(id, line)),
  onEngineExit: cb => ipcRenderer.on('engine:exit', (_e, id, code) => cb(id, code)),
  openEngineDialog: () => ipcRenderer.invoke('dialog:openEngine'),
  openKifuDialog: () => ipcRenderer.invoke('dialog:openKifu'),
  savePathDialog: name => ipcRenderer.invoke('dialog:savePath', name),
  writeText: (p, text) => ipcRenderer.invoke('file:writeText', p, text),
  openExternal: url => ipcRenderer.invoke('open:external', url),
  openDirDialog: title => ipcRenderer.invoke('dialog:openDir', title),
  autoSave: (dir, name, text) => ipcRenderer.invoke('file:autosave', dir, name, text),
  savePng: (dataUrl, name) => ipcRenderer.invoke('file:savePng', dataUrl, name),
  clipWriteImage: dataUrl => ipcRenderer.invoke('clip:writeImage', dataUrl),
  openImage: () => ipcRenderer.invoke('file:openImage'),
  csaConnect: (host, port) => ipcRenderer.invoke('csa:connect', host, port),
  csaSend: (id, line) => ipcRenderer.send('csa:send', id, line),
  csaClose: id => ipcRenderer.send('csa:close', id),
  onCsaLine: cb => ipcRenderer.on('csa:line', (_e, id, line) => cb(id, line)),
  onCsaClose: cb => ipcRenderer.on('csa:close', (_e, id, err) => cb(id, err)),
  bookGet: () => ipcRenderer.invoke('book:get'),
  bookSet: data => ipcRenderer.invoke('book:set', data),
  bookImport: () => ipcRenderer.invoke('book:import'),
  bookExport: text => ipcRenderer.invoke('book:export', text),
  captureBoard: (rect, mode, name) => ipcRenderer.invoke('capture:board', rect, mode, name),
  clipRead: () => ipcRenderer.invoke('clip:read'),
  clipWrite: text => ipcRenderer.invoke('clip:write', text),
  storeGet: () => ipcRenderer.invoke('store:get'),
  storeSet: data => ipcRenderer.invoke('store:set', data),
});
